[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "reporterman"
version = "1.1.2"
description = "A command-line tool to automate system audits with Metasploit. It is supported by some ollama LLMs."
requires-python = ">=3.12.3"
dependencies = [
    "typer",
    "ollama",
    "requests",
    "dotenv",
    "jinja2",
    "weasyprint",
    "pyfiglet",
    "colorama",
]

[project.scripts]
reporterman = "reporterman.main:app"
