def filter_response(input: str)-> str:

    output = input.strip()
    # YES, THE FILTER IS JUST A BUNCH OF HARDCODED INVALIDS RESPONSES
    if len(output) > 65:
        return ""
    elif len(output) < 5:
        return ""
    else:
        output = output.replace("and brain tissue By mimicking or blocking the action of natural hormones like estrogen","")
        output = output.replace("\n\nRULES (STRICT):\n- If input is already valid → output it EXACTLY as received","")
        output = output.replace("quotes around any item names to maintain raw data integrity for further processing by downstream systems within this pipeline","")
        output = output.replace("while removing explanations if present beforehand and ensuring no duplicates remain in your finalized list","")
        output = output.replace("output it exactly as received without any alterations or additional commentary","")
        output = output.replace("The CVE number was corrected to a plausible format and the duplicate item","")
        output = output.replace("Check if the input is already a valid list","")
        output = output.replace("which should not be part of the parsed content for our task here","")
        output = output.replace("removed duplicates","")
        output = output.replace("Removed duplicates","")
        output = output.replace("\"", "")
        output = output.replace("\n", "")
        output = output.replace("\\n", "")
        output = output.replace("\\t", "")
        output = output.replace("\n-", "")
        output = output.replace("If no valid list elements can be extracted from a given input","")
        output = output.replace("`","")
        output = output.replace("then you must return an empty string","")
        output = output.replace("Exploit", "")
        output = output.replace("exploit", "")
        output = output.replace("Exploit:", "")
        output = output.replace("exploit:", "")
        output = output.replace("If input does not", "")
        output = output.replace("thus preventing pipeline failure due to invalid input", "")
        output = output.replace("output an empty string to indicate","")
        output = output.replace("msexploit","")
        output = output.replace("This is an exploit that allows unauthorized access.","")
        output = output.replace(".","")
        output = output.replace("|","")
        output = output.replace("'","")
        output = output.replace(":","")
        output = output.replace(";","")
        output = output.replace("searchsploit","")
        output = output.replace("-m","")
        output = output.replace("end of instruction","")
        output = output.replace("Do not add","")
        output = output.replace("Remove any explanations","")
        output = output.replace("Vulnerability","")
        output = output.replace("vulnerability","")
        output = output.replace("SearchSploit","")
        output = output.replace("metasploit","")
        output = output.replace("vendor identifiers","")
        output = output.replace("plaintext","")
        output = output.replace("Output","")
        output = output.replace("output","")
        output = output.replace("-","")
        output = output.replace("item","")
        output = output.replace("item1","")
        output = output.replace("item2","")
        output = output.replace("item3","")
        output = output.replace("item4","")
        output = output.replace("item5","")
        output = output.replace("item6","") 
        output = output.replace("switch","")
        output = output.replace("router","")
        output = output.replace("firewall","")
        output = output.replace("explanations","")
        output = output.replace("Metasploit","")
        output = output.replace("neurological","")
        output = output.replace("reproductive","")
        output = output.replace("payload","")
        output = output.replace("3     1","")
        output = output.replace("3  4     1","")
        output = output.replace("To ensure compliance with your rules","")
        output = output.replace("and formatted as a commaseparated list)","")
        output = output.replace("and formatted as a commaseparated list","")
        output = output.replace("duplicates removed", "")
        output = output.replace("it will be  as an empty string","")

        if len(output) < 5:
            return ""
        else:
            return output
