import typer
from typing_extensions import Annotated
from reporterman.input_validations import (
    mode_validation,
    target_validation,
    ports_validation,
)
from reporterman.modules.reconnaissance.reconnaissance import reconnaissance
from reporterman.modules.data_analysis.data_analysis import data_analysis
from reporterman.database.database import (
    init_db,
    drop_db,
)
from reporterman.ollama_models.llm_handler import (
    soft_obs_analyzer,
    exploit_selector_vuln,
    exploit_selector_soft,
)
from reporterman.modules.execution.execution import execution
from reporterman.modules.reporting.reporting import generate_report
import ollama
import time

app = typer.Typer()


@app.command(help="Audit a given target. \
        It returns an autogenerated pdf with the results.")
def run(
    target: Annotated[
        str,
        typer.Argument(help="The target must be an IP direction, \
                    IP domain or a list of IPs"),
    ],
    mode: Annotated[
        int,
        typer.Option(
            "-m",
            "-mode",
            "--mode",
            help=(
                "The mode options specifies which \
                    target type will be processed.\n"
                "mode == 0: single IP\n"
                "mode == 1: IP domain\n"
                "mode == 2: list of IPs\n"
            ),
            callback=mode_validation,
        ),
    ] = 0,
    ports: Annotated[
        str,
        typer.Option(
            "-p",
            "-ports",
            "--ports",
            help="List of the ports that will be audited. \
                        It applies to each system in the modes 1 and 2",
        ),
    ] = "",
    path: Annotated[
        str,
        typer.Option(
            "-path",
            "--path",
            help="Output path for the generated report \
                        in pdf format",
        ),
    ] = None,
):
    start = time.time()
    print("validating inputs")
    target_validation(target, mode)
    ports_validation(ports)
    print("Running reconnaissance module")
    scan_output = reconnaissance(target, mode, ports)
    print("Selecting exploits")
    init_db()
    selected_exploits = data_analysis(scan_output)
    print("Exploit selection finished")
    execution(selected_exploits)
    print("Execution finished")
    total = time.time() - start
    total_min = int(total / 60)
    print(f"Total execution time {total_min}")
    generate_report(total_min, path)
    drop_db()


@app.command(
    name="llms-time-exec-test", help="Check how fast works the ollama models"  # noqa
)  # noqa
def llm_time_execution_test():
    client = ollama.Client()
    start = time.time()
    out1 = soft_obs_analyzer("service: telnet   other_info: ", client)
    out2 = soft_obs_analyzer("service: rexec   other_info: ", client)
    total = time.time() - start
    print("Expected soft analyzer outputs 1, 1")
    print(f"Actual outputs: {out1}, {out2}")
    print(f"Total execution time: {total}")

    print("-" * 100)

    start = time.time()
    print("Running exploit selector vuln")
    exploit_selector_vuln("CVE-2022-0540", client)  # noqa
    total = time.time() - start
    print(f"Total execution time: {total}")

    print("-" * 100)

    start = time.time()
    print("Running exploit selector soft")
    exploit_selector_soft("mysql port 3306 version 2.3", " ", client)  # noqa
    total = time.time() - start
    print(f"Total execution time: {total}")


"""
@app.command(name="report-test", help="generate a report for testing purposes")  # noqa
def informal_test_generate_report():

    start = time.time()
    total = time.time() - start
    total_min = int(total / 60)
    generate_report(total_min)
"""

if __name__ == "__main__":
    app()
