import typer
from typing_extensions import Annotated
from reporterman.input_validations import (
    mode_validation,
    target_validation,
    ports_validation,
)
from reporterman.modules.reconnaissance.reconnaissance import reconnaissance
from reporterman.modules.data_analysis.data_analysis import data_analysis
from reporterman.database.database import init_db
from reporterman.ollama_models.llm_handler import (
        soft_obs_analyzer,
        exploit_selector_soft,
        )
import ollama
import time

app = typer.Typer()


@app.command(help="Audit a given target. \
        It returns an autogenerated pdf with the results.")
def run(
    target: Annotated[
        str,
        typer.Argument(help="The target must be an IP direction, \
                    IP domain or a list of IPs"),
    ],
    mode: Annotated[
        int,
        typer.Option(
            "-m",
            "-mode",
            "--mode",
            help=(
                "The mode options specifies which \
                    target type will be processed.\n"
                "mode == 0: single IP\n"
                "mode == 1: IP domain\n"
                "mode == 2: list of IPs\n"
            ),
            callback=mode_validation,
        ),
    ] = 0,
    ports: Annotated[
        str,
        typer.Option(
            "-p",
            "-ports",
            "--ports",
            help="List of the ports that will be audited. \
                        It applies to each system in the modes 1 and 2",
        ),
    ] = "",
):
    print("validating inputs")
    target_validation(target, mode)
    ports_validation(ports)
    print("Running reconnaissance module")
    scan_output = reconnaissance(target, mode, ports)
    init_db()
    selected_exploits = data_analysis(scan_output)
    print(selected_exploits)


@app.command(name="llms-time-exec-test",
             help="Check how fast works the ollama models")
def llm_time_execution_test():
    client = ollama.Client()
    start = time.time()
    out1 = soft_obs_analyzer("service: telnet   other_info: ", client)
    out2 = soft_obs_analyzer("service: rexec   other_info: ", client)
    total = time.time() - start
    print("Expected soft analyzer outputs 1, 1")
    print(f"Actual outputs: {out1}, {out2}")
    print(f"Total execution time: {total}")

    start = time.time()
    out3 = exploit_selector_soft(["21/tcp","vsftpd","2.3.4","ftp-syst: \n|   STAT: \n| FTP server status:\n|      Connected to 192.168.1.13\n|      Logged in as ftp\n|      TYPE: ASCII\n|      No session bandwidth limit\n|      Session timeout in seconds is 300\n|      Control connection is plain text\n|      Data connections will be plain text\n|      vsFTPd 2.3.4 - secure, fast, stable\n|_End of status\n|_ftp-anon: Anonymous FTP login allowed (FTP code 230)]"], "", client)  # noqa
    print(out3)
    total = time.time() - start
    print(f"Total execution time: {total}")


if __name__ == "__main__":
    app()
