import typer
from typing_extensions import Annotated
from reporterman.input_validations import (
    mode_validation,
    target_validation,
    ports_validation,
)
from reporterman.modules.reconnaissance.reconnaissance import reconnaissance
from reporterman.utils.install_dependencies import set_up_dependencies


app = typer.Typer()


@app.command(
    help="Audit a given target. \
        It returns an autogenerated pdf with the results."
)
def run(
    target: Annotated[
        str,
        typer.Argument(
            help="The target must be an IP direction, \
                    IP domain or a list of IPs"
        ),
    ],
    mode: Annotated[
        int,
        typer.Option(
            "-m",
            "-mode",
            "--mode",
            help=(
                "The mode options specifies which \
                    target type will be processed.\n"
                "mode == 0: single IP\n"
                "mode == 1: IP domin\n"
                "mode == 2: list of IPs\n"
            ),
            callback=mode_validation,
        ),
    ] = 0,
    ports: Annotated[
        str,
        typer.Option(
            "-p",
            "-ports",
            "--ports",
            help="List of the ports that will be audited. \
                        It applies to each system in the modes 1 and 2",
        ),
    ] = "",
):
    print("validating inputs")
    target_validation(target, mode)
    ports_validation(ports)
    print("Running reconnaissance module")
    scan_output = reconnaissance(target, mode, ports)
    print(scan_output)


@app.command(
    name="setUp",
    help="Download all the required external dependencies"
    " such as nmap, metasploit or searchsploit."
    " It also creates the required llms",
)
def setUp():
    print("Installing all the ollama models and dependencies, please wait...")
    set_up_dependencies()


if __name__ == "__main__":
    app()
